### ISSUE TITLE
运行报错，帮看看什么情况

### ISSUE THREAD

**Issue by xyy55** [JMingZI/webchat#1]
在运行npm install& node server.js后报错
C:\下载\webchat-master\node_modules\socket.io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (C:\下载\webchat-master\node_modules\?[4msocket.io?[24m\lib\store.js:35:42)
?[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:815:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:852:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:74:18)?[39m
    at Object.<anonymous> (C:\下载\webchat-master\node_modules\?[4msocket.io?[24m\lib\manager.js:16:13)
?[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)?[39m

**Comment by itwxb** [comment]
首先需要把node文件夹删除 然后npm install 就好了  不过定位的少了代码 把这个加在jindex里就好	var remote_ip_info = {
		"ret": 1,
		"start": "1.192.0.0",
		"end": "1.193.127.255",
		"country": "\u4e2d\u56fd",
		"province": "\u6cb3\u5357",
		"city": "\u90d1\u5dde",

		"district": "",
		"isp": "\u7535\u4fe1",
		"type": "",
		"desc": ""
	}
